language: ruby
cache: bundler
bundler_args: "--without production"
services:
- postgresql
sudo: false
before_script:
- bundle install
- RAILS_ENV=development bundle exec rake db:create db:migrate
script:
  - bundle exec rubocop
  - bundle exec rspec
